var should = require('chai').should(),
    scapegoat = require('../index'),
    escape = scapegoat.escape,
    unescape = scapegoat.unescape;

var mark = require('../markovify/chain.js');

var test = [
    "I am not a free man! I am a number!",
    "Free the slaves",
    "I am a number of things",
    "LOL XDXDXDXDXD",
 "I JUST LITERALLY",
 "PEED",
 "MY",
 "PANTS",
 "JUST A LITTE THOUGH",
 "I MEAN ITS A LITTLE SPOT NOT LIKE IT RUINED MY CHAIR R NYTHING LOL BUT FOR REAL EPIC LULZ HIGH FIVES XDDDDDDDDDDDDDD",
 "U FRUSTRATED U FRUSTRATED BRO U SO MAD WHY ARE YOU SO MAAAAD I CAN POST ANYTHING I WANT THAT IS HOW IT SAYS IN THE RULES I DONT CARE ABOUT YOUR FAGGOTRY RULES Y SO MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD",
 "WHATA FUCK MAN xD i just fall of my chair kuz i couldnt and i CANT stop laugh xDXDXDXDXDDDDDDDDDDDDXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDD OMGOSH DDDDDXXXXXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDD LOOOOOOOOOLLLLL THIS IS A SHIT XDDDDDDDDDDDDDDDDDDDDXDDDDDDDDDDDDDDDDDDDDD A BIG ONE XDDDDDDDD A GRAT ONE XXXXXXDDDD CONGRATS MAN XD U FRUSTRATED U FRUSTRATED BRO U SO MAD WHY ARE YOU SO MAAAAD I CAN POST ANYTHING I WANT THAT IS HOW IT SAYS IN THE RULES I DONT CARE ABOUT YOUR FAGGOTRY RULES Y SO MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD",
 "WHATA FUCK MAN xD i just fall of my chair kuz i couldnt and i CANT stop laugh xDXDXDXDXDDDDDDDDDDDDXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDD OMGOSH DDDDDXXXXXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDD LOOOOOOOOOLLLLL THIS IS A SHIT hgXDDDDDDDDDDDDDDDDDDDDXDDDDDDDDDDDDDDDDDDDDD A BIG ONE XDDDDDDDD A GRAT ONE XXXXXXDDDD CONGRATS MAN XD",
 "WHATA FUCK MAN xD i just fall of my chair kuz i couldnt and i CANT stop laugh",
 "xDXDXDXDXDDDDDDDDDDDDXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDD OMGOSH",
 "HOOOOOOOOLLLLLLYYYYY SHIT",
 "whatr the HELL",
 "WHATA FUCK MAN xD",
 "i just fall of my chair kuz i couldnt and i CANT stop laugh",
 "xDXDXDXDXDDDDDDDDDDDDXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDD",
 "OMGOSH",
 "DDDDDXXXXXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDDDDDDDDDDD DDDDDD LOOOOOOOOOLLLLL",
 "THIS IS A SHIT",
 "XDDDDDDDDDDDDDDDDDDDDXDDDDDDDDDDDDDDDDDDDDD",
 "A BIG ONE",
 "XDDDDDDDD",
 "A GRAT ONE",
 "XXXXXXDDDD."
];
var bacon = {
  corpus:
   { I:
      [ 'am',
        'am',
        'am',
        'JUST',
        'MEAN',
        'CAN',
        'WANT',
        'DONT',
        'CAN',
        'WANT',
        'DONT' ],
     am: [ 'not', 'a', 'a' ],
     not: [ 'a' ],
     a: [ 'free', 'number!.', 'number' ],
     free: [ 'man!' ],
     'man!': [ undefined ],
     'number!.': [ undefined ],
     Free: [ 'the' ],
     the: [ 'slaves.', 'HELL.' ],
     'slaves.': [ undefined ],
     number: [ 'of' ],
     of: [ 'things.', 'my', 'my', 'my', 'my' ],
     'things.': [ undefined ],
     LOL: [ 'XDXDXDXDXD.', 'BUT' ],
     'XDXDXDXDXD.': [ undefined ],
     JUST: [ 'LITERALLY.', 'A' ],
     'LITERALLY.': [ undefined ],
     'PEED.': [ undefined ],
     'MY.': [ undefined ],
     'PANTS.': [ undefined ],
     A:
      [ 'LITTE',
        'LITTLE',
        'SHIT',
        'BIG',
        'GRAT',
        'SHIT',
        'BIG',
        'GRAT',
        'SHIT.',
        'BIG',
        'GRAT' ],
     LITTE: [ 'THOUGH.' ],
     'THOUGH.': [ undefined ],
     MEAN: [ 'ITS' ],
     ITS: [ 'A' ],
     LITTLE: [ 'SPOT' ],
     SPOT: [ 'NOT' ],
     NOT: [ 'LIKE' ],
     LIKE: [ 'IT' ],
     IT: [ 'RUINED', 'SAYS', 'SAYS' ],
     RUINED: [ 'MY' ],
     MY: [ 'CHAIR' ],
     CHAIR: [ 'R' ],
     R: [ 'NYTHING' ],
     NYTHING: [ 'LOL' ],
     BUT: [ 'FOR' ],
     FOR: [ 'REAL' ],
     REAL: [ 'EPIC' ],
     EPIC: [ 'LULZ' ],
     LULZ: [ 'HIGH' ],
     HIGH: [ 'FIVES' ],
     FIVES: [ 'XDDDDDDDDDDDDDD.' ],
     'XDDDDDDDDDDDDDD.': [ undefined ],
     U:
      [ 'FRUSTRATED',
        'FRUSTRATED',
        'SO',
        'FRUSTRATED',
        'FRUSTRATED',
        'SO' ],
     FRUSTRATED: [ 'U', 'BRO', 'U', 'BRO' ],
     BRO: [ 'U', 'U' ],
     SO:
      [ 'MAD',
        'MAAAAD',
        'MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD.',
        'MAD',
        'MAAAAD',
        'MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD.' ],
     MAD: [ 'WHY', 'WHY' ],
     WHY: [ 'ARE', 'ARE' ],
     ARE: [ 'YOU', 'YOU' ],
     YOU: [ 'SO', 'SO' ],
     MAAAAD: [ 'I', 'I' ],
     CAN: [ 'POST', 'POST' ],
     POST: [ 'ANYTHING', 'ANYTHING' ],
     ANYTHING: [ 'I', 'I' ],
     WANT: [ 'THAT', 'THAT' ],
     THAT: [ 'IS', 'IS' ],
     IS: [ 'HOW', 'A', 'HOW', 'A', 'A' ],
     HOW: [ 'IT', 'IT' ],
     SAYS: [ 'IN', 'IN' ],
     IN: [ 'THE', 'THE' ],
     THE: [ 'RULES', 'RULES' ],
     RULES: [ 'I', 'Y', 'I', 'Y' ],
     DONT: [ 'CARE', 'CARE' ],
     CARE: [ 'ABOUT', 'ABOUT' ],
     ABOUT: [ 'YOUR', 'YOUR' ],
     YOUR: [ 'FAGGOTRY', 'FAGGOTRY' ],
     FAGGOTRY: [ 'RULES', 'RULES' ],
     Y: [ 'SO', 'SO' ],
     'MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD.': [ undefined, undefined ],
     WHATA: [ 'FUCK', 'FUCK', 'FUCK', 'FUCK' ],
     FUCK: [ 'MAN', 'MAN', 'MAN', 'MAN' ],
     MAN: [ 'xD', 'XD', 'xD', 'XD.', 'xD', 'xD.' ],
     xD: [ 'i', 'i', 'i' ],
     i:
      [ 'just',
        'couldnt',
        'CANT',
        'just',
        'couldnt',
        'CANT',
        'just',
        'couldnt',
        'CANT',
        'just',
        'couldnt',
        'CANT' ],
     just: [ 'fall', 'fall', 'fall', 'fall' ],
     fall: [ 'of', 'of', 'of', 'of' ],
     my: [ 'chair', 'chair', 'chair', 'chair' ],
     chair: [ 'kuz', 'kuz', 'kuz', 'kuz' ],
     kuz: [ 'i', 'i', 'i', 'i' ],
     couldnt: [ 'and', 'and', 'and', 'and' ],
     and: [ 'i', 'i', 'i', 'i' ],
     CANT: [ 'stop', 'stop', 'stop', 'stop' ],
     stop: [ 'laugh', 'laugh', 'laugh.', 'laugh.' ],
     laugh:
      [ 'xDXDXDXDXDDDDDDDDDDDDXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDD',
        'xDXDXDXDXDDDDDDDDDDDDXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDD' ],
     xDXDXDXDXDDDDDDDDDDDDXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDD: [ 'OMGOSH', 'OMGOSH', 'OMGOSH.' ],
     OMGOSH:
      [ 'DDDDDXXXXXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
        'DDDDDXXXXXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD' ],
     DDDDDXXXXXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD: [ 'DDDDDD', 'DDDDDD' ],
     DDDDDD: [ 'LOOOOOOOOOLLLLL', 'LOOOOOOOOOLLLLL', 'LOOOOOOOOOLLLLL.' ],
     LOOOOOOOOOLLLLL: [ 'THIS', 'THIS' ],
     THIS: [ 'IS', 'IS', 'IS' ],
     SHIT:
      [ 'XDDDDDDDDDDDDDDDDDDDDXDDDDDDDDDDDDDDDDDDDDD',
        'hgXDDDDDDDDDDDDDDDDDDDDXDDDDDDDDDDDDDDDDDDDDD' ],
     XDDDDDDDDDDDDDDDDDDDDXDDDDDDDDDDDDDDDDDDDDD: [ 'A' ],
     BIG: [ 'ONE', 'ONE', 'ONE.' ],
     ONE: [ 'XDDDDDDDD', 'XXXXXXDDDD', 'XDDDDDDDD', 'XXXXXXDDDD' ],
     XDDDDDDDD: [ 'A', 'A' ],
     GRAT: [ 'ONE', 'ONE', 'ONE.' ],
     XXXXXXDDDD: [ 'CONGRATS', 'CONGRATS' ],
     CONGRATS: [ 'MAN', 'MAN' ],
     XD: [ 'U' ],
     hgXDDDDDDDDDDDDDDDDDDDDXDDDDDDDDDDDDDDDDDDDDD: [ 'A' ],
     'XD.': [ undefined ],
     'laugh.': [ undefined, undefined ],
     'OMGOSH.': [ undefined, undefined ],
     HOOOOOOOOLLLLLLYYYYY: [ 'SHIT.' ],
     'SHIT.': [ undefined, undefined ],
     whatr: [ 'the' ],
     'HELL.': [ undefined ],
     'xD.': [ undefined ],
     'xDXDXDXDXDDDDDDDDDDDDXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDD.': [ undefined ],
     DDDDDXXXXXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDDDDDDDDDDD: [ 'DDDDDD' ],
     'LOOOOOOOOOLLLLL.': [ undefined ],
     'XDDDDDDDDDDDDDDDDDDDDXDDDDDDDDDDDDDDDDDDDDD.': [ undefined ],
     'ONE.': [ undefined, undefined ],
     'XDDDDDDDD.': [ undefined ],
     'XXXXXXDDDD..': [ undefined ] },
  start:
   [ 'I',
     'I',
     'Free',
     'I',
     'LOL',
     'I',
     'PEED.',
     'MY.',
     'PANTS.',
     'JUST',
     'I',
     'U',
     'WHATA',
     'WHATA',
     'WHATA',
     'xDXDXDXDXDDDDDDDDDDDDXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDD',
     'HOOOOOOOOLLLLLLYYYYY',
     'whatr',
     'WHATA',
     'i',
     'xDXDXDXDXDDDDDDDDDDDDXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDD.',
     'OMGOSH.',
     'DDDDDXXXXXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
     'THIS',
     'XDDDDDDDDDDDDDDDDDDDDXDDDDDDDDDDDDDDDDDDDDD.',
     'A',
     'XDDDDDDDD.',
     'A',
     'XXXXXXDDDD..' ]
 }

describe('#escape', function() {
  it('test converts into test', function() {
		new mark.Chain(test).should.equal(bacon);
  });

});

module.exports = {
  Chain: mark.Chain,
  markov: mark.markov
}
